{{- define "common.internal.secret" -}}
{{- range $secret, $items := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret }}
{{ include "common.imetadata" $ | indent 2 }}
type: Opaque
data:
  {{- range $key, $value := $items }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
{{- end -}}
