replicaCount: 1

image:
  repository: ghcr.io/stoyan-z-yanev/stoyan-z-yanev/devops-task
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

pgadmin:
  image: "dpage/pgadmin4"
  tag: "latest"

postgresql:
  primary:
    initdb:
      scripts:
        init.sql: |
          CREATE TABLE IF NOT EXISTS crypto_data (
                id SERIAL PRIMARY KEY,
                name VARCHAR(255),
                symbol VARCHAR(10),
                price NUMERIC
            )
  audit:
    logConnections: true